version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    resource_class: small
    steps:
      - checkout
      - run:
          name: Setup Maven Toolchains
          command: |
            mkdir -p ~/.m2
            cat > ~/.m2/toolchains.xml <<'EOF'
            <toolchains>
              <toolchain>
                <type>jdk</type>
                <provides>
                  <version>21</version>
                  <vendor>openjdk</vendor>
                </provides>
                <configuration>
                  <jdkHome>/usr/lib/jvm/java-21-openjdk-amd64</jdkHome>
                </configuration>
              </toolchain>
            </toolchains>
            EOF
      - run:
          name: Build and Test
          command: mvn -B clean verify

workflows:
  sample:
    jobs:
      - build-and-test
